# -*- coding: utf-8 -*-
"""assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMVPY8knrzFII4TrtXEvN3si6ZdsIrBz
"""

a=int(input("enter the value of a"))
if(a>18):
  print("a is eligible for vote")
else:
     print("a is not eligible for vote")

a=int(input("enter the value of a"))
if(a%2)==0:
  print("{0} is even number".format(a))
else:
     print("{0} is odd number".format(a))

a=str(input("enter a string:"))
print("reverse of string is:")
print(a[::-1])

n=int(input("enter number"))
if(n>0):
  print("number is positive")
else:
     print("number is negative")

import math
a=float(input("enter the coefficient a"))
b=float(input("enter the coefficient b"))
c=float(input("enter the coefficient c"))
d=b*b-4*a*c;
if d>0:
  r1=(-b+math.sqrt(d))/(2*a)
  r2=(-b-math.sqrt(d))/(2*a)
  print("roots are real and unequal",r1,"and",r2)
elif d==0:
    r1=-b/(2*a)
    print("roots are real and same", r1)
else:
     print("no real roots are there")

num=float(input("enter a number"))
if num>=0:
  if num==0:
    print("zero")
  else:
       print("positive number")      
else:
       print("negative number")

number=(" ","one","two","three","four","five")
n=int(input("enter a number"))
print(number[n])

ch=input("enter a character")
if(ch=='A' or ch=='a' or ch=='E' or ch=='e' or ch=='I' or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'):
  print(ch,"is a vowel")
else:
     print(ch,"is a consonant")

